CREATE DATABASE IF NOT EXISTS demo_boxoffice;
USE demo_boxoffice;

CREATE TABLE IF NOT EXISTS movies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  movie_name VARCHAR(255) NOT NULL,
  hero VARCHAR(255) NOT NULL,
  collection DECIMAL(12,2) NOT NULL,
  status ENUM('running','left') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
